/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tea.pink;

import java.util.ArrayList;

/**
 *
 * @author USER
 */
public class AVERAGE_JFRAME extends javax.swing.JFrame {

    /**
     * Creates new form AVERAGE_JFRAME
     */
    public AVERAGE_JFRAME(ArrayList<String> USER_INFO) {
        initComponents();
        USERNAME_JFRAME.setText(""+ USER_INFO.get(0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        AVG_BIG_JFRAME = new javax.swing.JLabel();
        AVG_JFRAME = new javax.swing.JLabel();
        ACC_JFRAME = new javax.swing.JLabel();
        CORRECT_JFRAME = new javax.swing.JLabel();
        WRONG_JFRAME = new javax.swing.JLabel();
        USERNAME_JFRAME = new javax.swing.JLabel();
        WPM_LBL = new javax.swing.JLabel();
        EXIT_JFRAME = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(153, 0, 153));

        AVG_BIG_JFRAME.setFont(new java.awt.Font("Poppins", 1, 80)); // NOI18N
        AVG_BIG_JFRAME.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AVG_BIG_JFRAME.setText("0");

        AVG_JFRAME.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        AVG_JFRAME.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        AVG_JFRAME.setText("AVERAGE               : 0 wpm");

        ACC_JFRAME.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        ACC_JFRAME.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ACC_JFRAME.setText("ACCURACY          : 0 %");

        CORRECT_JFRAME.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        CORRECT_JFRAME.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CORRECT_JFRAME.setText("CORRECT              : 0 words");

        WRONG_JFRAME.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        WRONG_JFRAME.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        WRONG_JFRAME.setText("WRONG                 : 0 words");

        USERNAME_JFRAME.setFont(new java.awt.Font("Poppins", 1, 36)); // NOI18N
        USERNAME_JFRAME.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        USERNAME_JFRAME.setText("MUHAMMAD IDRIS");

        WPM_LBL.setFont(new java.awt.Font("Poppins", 1, 10)); // NOI18N
        WPM_LBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WPM_LBL.setText("Words Per Minute");

        EXIT_JFRAME.setFont(new java.awt.Font("Poppins ExtraBold", 1, 36)); // NOI18N
        EXIT_JFRAME.setForeground(java.awt.Color.black);
        EXIT_JFRAME.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EXIT_JFRAME.setText("X");
        EXIT_JFRAME.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EXIT_JFRAMEMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(AVG_BIG_JFRAME, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(WPM_LBL)
                        .addGap(64, 64, 64)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AVG_JFRAME, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ACC_JFRAME, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CORRECT_JFRAME, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                    .addComponent(WRONG_JFRAME, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(USERNAME_JFRAME)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(EXIT_JFRAME, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(USERNAME_JFRAME))
                    .addComponent(EXIT_JFRAME, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(AVG_JFRAME, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ACC_JFRAME, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CORRECT_JFRAME, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(AVG_BIG_JFRAME)
                        .addGap(37, 37, 37)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(WRONG_JFRAME, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WPM_LBL))
                .addGap(69, 69, 69))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EXIT_JFRAMEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EXIT_JFRAMEMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_EXIT_JFRAMEMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AVERAGE_JFRAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AVERAGE_JFRAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AVERAGE_JFRAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AVERAGE_JFRAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AVERAGE_JFRAME().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ACC_JFRAME;
    private javax.swing.JLabel AVG_BIG_JFRAME;
    private javax.swing.JLabel AVG_JFRAME;
    private javax.swing.JLabel CORRECT_JFRAME;
    private javax.swing.JLabel EXIT_JFRAME;
    private javax.swing.JLabel USERNAME_JFRAME;
    private javax.swing.JLabel WPM_LBL;
    private javax.swing.JLabel WRONG_JFRAME;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
