/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tea.pink;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author MUHAMMAD IDRIS
 * @author TARA ALMANDA
 * @author IVANKA AUDY IKHWAN
 */
public class Login extends javax.swing.JFrame {

    /**
     * Deklarasi Variabel USERNAME = username dimasukkan di dalam var ini
     * ALL_USERNAME = var untuk arraylist username , semua username dimasukkan
     * kedalam sini
     */
    ArrayList<String> ALL_USERNAME = new ArrayList<>();

    //deklarasi variabel end
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TP_LBL = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LOGIN_BTN = new javax.swing.JButton();
        USERNAME_TEXT = new javax.swing.JTextField();
        ALERT_LBL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TEA-PINK");

        jPanel1.setBackground(java.awt.Color.red);
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TP_LBL.setFont(new java.awt.Font("Lemon Days", 1, 40)); // NOI18N
        TP_LBL.setForeground(new java.awt.Color(102, 0, 0));
        TP_LBL.setText("TEA-PINK");
        jPanel1.add(TP_LBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 12, -1, 60));

        jLabel2.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 0));
        jLabel2.setText("LOGIN");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 181, -1, -1));

        LOGIN_BTN.setBackground(java.awt.Color.blue);
        LOGIN_BTN.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        LOGIN_BTN.setText("Log In");
        LOGIN_BTN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        LOGIN_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOGIN_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(LOGIN_BTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 421, 130, 37));

        USERNAME_TEXT.setBackground(java.awt.Color.white);
        USERNAME_TEXT.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        USERNAME_TEXT.setForeground(java.awt.Color.gray);
        USERNAME_TEXT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        USERNAME_TEXT.setText("USERNAME");
        USERNAME_TEXT.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        USERNAME_TEXT.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                USERNAME_TEXTInputMethodTextChanged(evt);
            }
        });
        USERNAME_TEXT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                USERNAME_TEXTKeyReleased(evt);
            }
        });
        jPanel1.add(USERNAME_TEXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 217, 46));

        ALERT_LBL.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        ALERT_LBL.setForeground(java.awt.Color.black);
        ALERT_LBL.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ALERT_LBL.setText("* Maximum 15 Character");
        jPanel1.add(ALERT_LBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LOGIN_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOGIN_BTNActionPerformed
        // TODO add your handling code here:
        String USERNAME = USERNAME_TEXT.getText().toUpperCase();

        if (USERNAME.equals("")) {
            JOptionPane.showMessageDialog(null, "Username still Blank, PLease input username!", "A message", JOptionPane.OK_OPTION);
        } else {
            int input = JOptionPane.showConfirmDialog(null, ("SELAMAT DATANG " + USERNAME + "!"), "Message", JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE);
            if (input == 0) {
                // add username to ALL_USERNAME(arraylist)
                ALL_USERNAME.add(USERNAME);

                // to TYPEE page
                TYPEE Type = new TYPEE();
                Type.setLocationRelativeTo(null);
                Type.setVisible(true);
                this.setVisible(false);
            }
        }
    }//GEN-LAST:event_LOGIN_BTNActionPerformed

    private void USERNAME_TEXTInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_USERNAME_TEXTInputMethodTextChanged
        // TODO add your handling code here:
        String USERNAME = USERNAME_TEXT.getText().toUpperCase();


    }//GEN-LAST:event_USERNAME_TEXTInputMethodTextChanged

    private void USERNAME_TEXTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_USERNAME_TEXTKeyReleased
        // TODO add your handling code here:
        String USERNAME = USERNAME_TEXT.getText();
        String USERNAME_15 = USERNAME.substring(0,15);
        if (USERNAME.length() > 15) {
            USERNAME_TEXT.setText(USERNAME_15);
        }
    }//GEN-LAST:event_USERNAME_TEXTKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ALERT_LBL;
    private javax.swing.JButton LOGIN_BTN;
    private javax.swing.JLabel TP_LBL;
    private javax.swing.JTextField USERNAME_TEXT;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    ArrayList<String> ALL_USERNAME() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
