/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tea.pink;

import java.awt.*;
import java.util.*;
import javax.swing.*;

/**
 *
 * @author MUHAMMAD IDRIS
 * @author TARA ALMANDA
 * @author IVANKA AUDY IKHWAN
 */
public class Login extends javax.swing.JFrame {

    // DEKLARASI 3 ARRAY EASY, MEDIUM, DAN HARD 
    ArrayList<String> EASY_;
    ArrayList<String> MEDIUM_;
    ArrayList<String> HARD_;

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setExtendedState(Home.MAXIMIZED_BOTH);

    }

    public void USER(ArrayList<String> EASY, ArrayList<String> MEDIUM, ArrayList<String> HARD) {
        try {
            // INIZIALIZATION 3 ARRAY
            EASY_ = EASY;
            MEDIUM_ = MEDIUM;
            HARD_ = HARD;
//            ALERT_LBL.setText("" + EASY_);
        } catch (IndexOutOfBoundsException e) {
            System.out.println("ARRAY IS NOT EMPTY");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        LOGIN_BTN = new javax.swing.JButton();
        USERNAME_TEXT = new javax.swing.JTextField();
        ALERT_LBL = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TEA-PINK");
        setBackground(new java.awt.Color(93, 120, 58));
        setPreferredSize(new java.awt.Dimension(1380, 900));

        jPanel1.setBackground(new java.awt.Color(93, 120, 58));
        jPanel1.setMinimumSize(new java.awt.Dimension(1400, 900));
        jPanel1.setPreferredSize(new java.awt.Dimension(1500, 1000));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Username");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 350, -1));

        LOGIN_BTN.setBackground(new java.awt.Color(87, 125, 38));
        LOGIN_BTN.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        LOGIN_BTN.setText("Log In");
        LOGIN_BTN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        LOGIN_BTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LOGIN_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOGIN_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(LOGIN_BTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 580, 130, 37));

        USERNAME_TEXT.setBackground(new java.awt.Color(200, 224, 168));
        USERNAME_TEXT.setColumns(15);
        USERNAME_TEXT.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        USERNAME_TEXT.setForeground(java.awt.Color.gray);
        USERNAME_TEXT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        USERNAME_TEXT.setText("USERNAME");
        USERNAME_TEXT.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(101, 131, 62), null));
        USERNAME_TEXT.setCaretColor(new java.awt.Color(101, 131, 62));
        USERNAME_TEXT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                USERNAME_TEXTFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                USERNAME_TEXTFocusLost(evt);
            }
        });
        USERNAME_TEXT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                USERNAME_TEXTKeyReleased(evt);
            }
        });
        jPanel1.add(USERNAME_TEXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 350, 46));

        ALERT_LBL.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        ALERT_LBL.setForeground(new java.awt.Color(0, 255, 204));
        ALERT_LBL.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ALERT_LBL.setText("* Maximum 15 Character");
        jPanel1.add(ALERT_LBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, 350, -1));

        jLabel3.setForeground(new java.awt.Color(153, 153, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/tea/pink/iconImage/Component 3.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 1100, 650));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/tea/pink/iconImage/Backgorund1.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(1370, 900));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 900));

        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LOGIN_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOGIN_BTNActionPerformed
        String USERNAME = USERNAME_TEXT.getText();

        if (USERNAME.equals("") || USERNAME.equals("USERNAME")) {
            JOptionPane.showMessageDialog(null, "Username still Blank, PLease input username!", "A message", JOptionPane.OK_OPTION);
        } else {
            int input = JOptionPane.showConfirmDialog(null, ("Your Username is " + USERNAME + " ? "), "Message", JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE);
            if (input == 0) {
                // to TYPEE page
                Type_Easy Type = new Type_Easy();
                Type.USER(USERNAME, EASY_, MEDIUM_, HARD_);
                Type.setLocationRelativeTo(null);
                Type.setVisible(true);
                this.setVisible(false);
            }
        }
    }//GEN-LAST:event_LOGIN_BTNActionPerformed

    private void USERNAME_TEXTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_USERNAME_TEXTKeyReleased
        // TODO add your handling code here:
        String USERNAME = USERNAME_TEXT.getText();

        int a = evt.getKeyCode();
        if (a == 10) {
            if (USERNAME.equals("") || USERNAME.equals("USERNAME")) {
                JOptionPane.showMessageDialog(null, "Username still Blank, PLease input username!", "A message", JOptionPane.OK_OPTION);
            } else {
                int input = JOptionPane.showConfirmDialog(null, ("Your Username is " + USERNAME + " ? "), "Message", JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE);
                if (input == 0) {
                    // to TYPEE page
                    Type_Easy Type = new Type_Easy();
                    Type.USER(USERNAME, EASY_, MEDIUM_, HARD_);
                    Type.setLocationRelativeTo(null);
                    Type.setVisible(true);
                    this.setVisible(false);
                }
            }
        }
        try {
            String USERNAME_15 = USERNAME.substring(0, 14);  // GET USERNAME SUBSTRING OF 1 - 14
            if (USERNAME.length() >= 15) {
                USERNAME_TEXT.setText(USERNAME_15);
            } else {
                USERNAME_TEXT.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.black));
                ALERT_LBL.setForeground(Color.black);
            }
        } catch (IndexOutOfBoundsException e) {
            ALERT_LBL.setForeground(Color.RED);
            USERNAME_TEXT.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.red));
        }
    }//GEN-LAST:event_USERNAME_TEXTKeyReleased

    private void USERNAME_TEXTFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_USERNAME_TEXTFocusGained
        // TODO add your handling code here:
        USERNAME_TEXT.setText("");
        ALERT_LBL.setForeground(Color.black);
        USERNAME_TEXT.setBackground(Color.white);
        USERNAME_TEXT.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.black));
    }//GEN-LAST:event_USERNAME_TEXTFocusGained

    private void USERNAME_TEXTFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_USERNAME_TEXTFocusLost
        // TODO add your handling code here:
        String USERNAME = USERNAME_TEXT.getText();
        if (USERNAME.equals("")) {
            USERNAME_TEXT.setText("USERNAME");
        }
        USERNAME_TEXT.setBackground(new java.awt.Color(200,224,168));

        USERNAME_TEXT.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, null));
        ALERT_LBL.setForeground(Color.black);
    }//GEN-LAST:event_USERNAME_TEXTFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ALERT_LBL;
    private javax.swing.JButton LOGIN_BTN;
    private javax.swing.JTextField USERNAME_TEXT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
